# Generated by Django 4.0.2 on 2022-05-03 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[], max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RecipePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Recipe Title', max_length=200)),
                ('author', models.CharField(default='Author', max_length=200)),
                ('ingredients', models.TextField(default='Ingredients')),
                ('intro', models.TextField(default='Instructions')),
                ('cook_time', models.IntegerField(default=0)),
                ('servings', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipe_image', models.ImageField(default='images/wordofmouth.png', upload_to='images/')),
                ('saved', models.ManyToManyField(blank=True, default=None, related_name='saved', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
